version: '3.9'   #  kaže Dockeru koju verziju pravila za pisanje ovog fajla da koristi

services: # Ovde se definišu kontejnere(servise) koji se pokrecu

  neo4j:
    image: neo4j:5   # konkretna verzija
    container_name: game-rec-neo4j   # ime u docker-u
    restart: unless-stopped   # ako se sruši, sam se restartuje
    
    ports:
      - "7474:7474"     # port za Neo4j Web Interfejs (http://localhost:7474)
      - "7687:7687"     # port preko kog Backend(kod) priča sa bazom
    
    volumes:
      - neo4j-data:/data               # Sve što Neo4j sačuva u /data (gde inače čuva grafove), preusmeravamo van kontejnera na mesto neo4j-data
      - ./neo4j-seed:/docker-entrypoint-initdb.d   # zove moju skriptu sa kojom puni bazu

    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}   # kontejneru treba sifra, ta sifra se vuce iz .env fajla

  backend:
    build: .                           # gradi contajner na osnovu Dockerfile-a koji je u istom folderu
    container_name: game-rec-api
    restart: unless-stopped
    
    ports:
      - "5257:5257"                    # port na kom ce biti container
    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5257
      # Sve ostale varijable dolaze iz .env fajla
      # (Neo4j__Uri ćeš override-ovati dole)
    
    env_file:
      - .env                           # kada se pali bekcend svi potrebni podaci se vuku iz .env 
    
    depends_on:
      - neo4j                        # pokreće Neo4j pre backend-a
    
    extra_hosts:
      - "host.docker.internal:host-gateway"   # da bi pristupi host mašini

volumes:
  neo4j-data:

